apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
type: Opaque
data:
  # base64-encoded values
  MONGO_URI: bW9uZ29kYjovL3J1Y2hpcmF0aGFyYW5rYTE6UmNFbXRCWXgyeVZTNUFyRUBhYy1jZ3VocDJ5LXNoYXJkLTAwLTAwLnVwOTEwdnoubW9uZ29kYi5uZXQ6MjcwMTcsYWMtY2d1aHAyeS1zaGFyZC0wMC0wMS51cDkxMHZ6Lm1vbmdvZGIubmV0OjI3MDE3LGFjLWNndWhwMnktc2hhcmQtMDAtMDIudXA5MTB2ei5tb25nb2RiLm5ldDoyNzAxNy8/cmVwbGljYVNldD1hdGxhcy1xNjk5anYtc2hhcmQtMCZzc2w9dHJ1ZSZhdXRoU291cmNlPWFkbWluJnJldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPXBheW1lbnQ=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVI3Qm9MRDM4NzlhSkduUGYwd293cE04TUZxRlc1czVMcE1BczBZVXc1TXh6d3NDdFdmTVdCc0lQRWxnRVBzV0JaM0Vnb1RVbHBPUThjOW9FMjRreVB6STAwVlZRYmxqT2s=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfYjg4ZWFlMmQ4YTA0MGZmZDQ1NmVlMTllZTA3Y2U4YjIzNzJlMDU2NWNjMzgyN2RjZjgwMjU4MzkwOWVkNjA4Nw==
  TWILIO_ACCOUNT_SID: QUM1ZDhhODhiMWJiMDJmMWVkNTU1OTllMDNhMmI0MWRhMg==
  TWILIO_AUTH_TOKEN: YzFkZTNkMjMzOTRiOTAxZjA5ODNkN2FhMzMwMzlhNGI=
  TWILIO_PHONE_NUMBER: KzE5NzE0MDYyNjg5
  RESEND_API_KEY: cmVfUVlOZTJQNHVfSHBZVTVNeFRDNzdMNUZ4OEZpV0JxbVU0
